atlas-trips/atlas

client/components/AccommodationOverview.js
client/components/SingleTrip.js

just dummy data in overview for now

Accommodation overview fix

---

client/components/SingleTrip.js
script/seed.js

updated seed with more sample data to play with

Seed update

---

script/seed.js
server/db/models/index.js
server/db/models/travel.js

created Travel model, updated seed so join tables get populated

update seed and models so join tables are populated

---

client/components/TripForm.js
package-lock.json
server/api/trips.js
server/index.js

comment out remaining socket references
fix padding on new trip dates causing errors

remove sockets fix dates

---

client/components/AccommodationForm.js
client/components/Accommodations.js
client/components/Sidebar.js
client/store/accommodation.js
client/store/history.js
server/api/trips.js

prettify files

---

server/index.js

update seed to wipe heroku db and re-seed

---

server/index.js

finished clearing heroku db

---

client/components/SearchMap.js

change onboundschange func to make map able to continuously be scrolled

make map able to continuously be dragged around

---

server/api/trips.js
server/api/utils.js

add a route in trips so that all relevant info for a single trip is delivered and cleaned into an object that can be served to the front end

add a route to obtain all relevant issue for a trip

---

client/components/Activities.js

- when new activity is created, immediately renders on page

renders new activity on view

---

client/components/Activities.js
client/components/ActivitiesForm.js

Took the activities form out of the activities component and created a new subcomponent for it.

refactor activities page by creating new subcomponent

---

client/components/Activities.js
client/components/ActivitiesForm.js
client/components/AllTrips.js
client/components/Dashboard.js
client/components/SearchMap.js
client/components/ShareTrip.js
client/components/SingleTrip.js
package-lock.json
package.json
public/style.css
server/api/utils.js

- added modal for invite friends to trip
- modal closes on completion
- will style later

add modal for sharing trip with friends

---

client/components/AuthForm.js
client/store/user.js
script/seed.js
server/api/trips.js
server/auth/index.js

Email notifications

---

client/components/Dashboard.js
client/components/TripForm.js
public/style.css

added css so the form looks presentable. added sidebar, because the page contained no way to navigate

Add trip css

---

client/components/AccommodationForm.js
client/components/AllTrips.js
client/components/Sidebar.js
public/style.css

added css stylings for new accommo form

added styling to add accommodation form that mimics add trip form

---

client/components/AccommodationForm.js
client/components/Accommodations.js
client/components/TripForm.js
public/style.css

added accommodation cards on accommo page, fixed buttons on forms to read "submit"

added accommodation cards, minor css fixes

---

client/components/AccommodationForm.js
client/components/Accommodations.js
client/components/AuthForm.js
client/components/TripForm.js
public/style.css
server/api/trips.js
server/auth/index.js

fix for heroku and prettify

---

client/components/Accommodations.js
client/store/accommodation.js
public/style.css
server/api/accommodations.js

you can now delete accommodations from a trip

---

client/components/Dashboard.js

add a trip button exists when you have no trips

---

client/components/AccommodationOverview.js
client/components/ActivitiesOverview.js
client/components/ParticipantsOverview.js
client/components/SingleTrip.js
public/style.css

made cards for single trip component

---

client/components/Accommodations.js
client/components/Calendar.js
public/style.css
server/api/accommodations.js

now if you have no itinerary and go to calendar you will be told that and be given links to other sections to add things

add basic styling for situation where no itinerary

---

client/components/SingleTrip.js
public/style.css

Single trip styling

---

client/components/SingleTrip.js

fixed issue with modal not sending email

---

client/components/ActivitiesForm.js
client/components/AuthForm.js
client/components/Calendar.js
client/components/ParticipantsOverview.js
client/components/Sidebar.js
client/components/SingleTrip.js
client/store/user.js
public/style.css
server/auth/index.js

- single trp fix - when new user adds a trip
- other fixes

Fix SingleTrip when new user adds trip

---

client/components/SingleTrip.js

 fix change

---

client/components/Travel.js
client/components/TravelForm.js
server/api/trips.js

Travel fix

---

client/components/Accommodations.js
client/components/Activities.js
client/components/Calendar.js
client/components/Dashboard.js
client/components/Header.js
client/components/SingleTrip.js
client/components/Travel.js
client/components/index.js
public/style.css

added header that shows current trip

---

client/components/ActivitiesForm.js
client/components/TravelForm.js
public/style.css

Disable buttons

---

client/components/Travel.js
public/style.css

fixed ability to change calendar months
